env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
    arrowFunctions: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - react
  - react-hooks
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies:
    - 2
    - devDependencies:
        - '**/*.test.tsx'
        - '**/*.test.ts'
        - '**/test.tsx'
        - '**/test.ts'
  indent: 'off'
  no-use-before-define: 'off'
  no-unused-vars: 'off'
  react/jsx-filename-extension:
    - 2
    - extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  react/jsx-indent: 'off'
  react/jsx-one-expression-per-line: 'off'
  '@typescript-eslint/indent': 'off'
  '@typescript-eslint/no-empty-function':
    - error
    - allow:
        - 'private-constructors'
  '@typescript-eslint/no-use-before-define':
    - error
settings:
  import/resolver:
    typescript:
  react:
    version: detect
